### ISSUE TITLE
how specify community plugin for GeoServer deploy

### ISSUE THREAD

**Issue by lstillwe** [kartoza/charts#46]
How does one specify community plugins to be added for the GeoServer deploy?

**Comment by NyakudyaA** [comment]
> How does one specify community plugins to be added for the GeoServer deploy?

I haven't deployed using charts yet but since in the normal docker-compose you can pass the env variable i.e `COMMUNITY_EXTENSIONS=gwc-sqlite-plugin`
this can be defined in the chart https://github.com/kartoza/charts/blob/develop/charts/geoserver/v0.3.1/values.yaml#L20
