### ISSUE TITLE
[GeoServer] 0.3.2 & 0.3.3 not available at helm repo

### ISSUE THREAD

**Issue by bmaguireibm** [kartoza/charts#61]
Thank you for these excellent charts!

It appears the helm repo: https://kartoza.github.io/charts most recent version of GeoServer is v0.3.1 but 0.3.2 & 0.3.3 are available in Github, is it possible for the updated charts to be added to https://kartoza.github.io/charts?

Thank you & regards, 

Brian

**Comment by bstrdsmkr** [comment]
+1 we're also waiting for these to be released to the repo :D

Specifically, the ingress in 0.3.1 is still in the beta namespace so it doesn't work with newer versions of k8s

**Comment by NyakudyaA** [comment]
@bmaguireibm @bstrdsmkr @mrpotato3 I urge you to take the initiative and do a PR, we will review and merge. We sometimes get too busy with client work and do not spend as much time as we would like wit these pro bono work

**Comment by bmaguireibm** [comment]
@NyakudyaA  Thanks for the reply, I'm happy to have a look, but would need some pointers I'm afraid. Just from reviewing the repo it's not clear what mechanism is used to publish the charts on release and why it didn't work for 0.3.3. Would you be able to point me in the right direction ?

Thanks and Best regards, 

Brian

**Comment by bmaguireibm** [comment]
Nevermind, I believe I've figured it out how the releases are triggered. It looks like the last commit to main this time last year had a failure in the "release" job. Unfortunately, the logs are no longer available for that run. Is it possible to manually trigger it again?

https://github.com/kartoza/charts/actions/runs/3106124764/job/8495779743

**Comment by NyakudyaA** [comment]
It looks like we cannot rerun that job, maybe just push a commit to that branch and it will start the job again

**Comment by filatovw** [comment]
@bmaguireibm Hi! Today CI job was fixed. Could you please sync the latest changes into your branch so the PR may finally be reviewed and merged? I cannot push changes to your repo, unfortunately.

**Comment by NyakudyaA** [comment]
> @bmaguireibm Hi! Today CI job was fixed. Could you please sync the latest changes into your branch so the PR may finally be reviewed and merged? I cannot push changes to your repo, unfortunately.

Alternatively you can cherry pick those changes and do a new PR, since most people are on holiday already
